### ISSUE TITLE
[Error] Build on OS X 10.10.3 (14D105g)

### ISSUE THREAD

**Issue by fzzr-** [tong/hxssl#39]
OS X 10.10.3 (14D105g) & latest Xcode.
Log:
```log
$ make

Building ndll for Mac64 (x86_64)

g++ -c -fvisibility=hidden -stdlib=libstdc++ -O2 -I/Users/ak/Developer/Haxe/libs/hxcpp/3,2,37/include -DHX_MACOS -m64 -Wno-parentheses -Wno-unused-value -Wno-format-extra-args -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=0 -x c++ -frtti -Wno-invalid-offsetof ./hxssl_ssl.cpp -oobj/darwin64/849d656e_hxssl_ssl.o
g++ -c -fvisibility=hidden -stdlib=libstdc++ -O2 -I/Users/ak/Developer/Haxe/libs/hxcpp/3,2,37/include -DHX_MACOS -m64 -Wno-parentheses -Wno-unused-value -Wno-format-extra-args -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=0 -x c++ -frtti -Wno-invalid-offsetof ./hxssl_md5.cpp -oobj/darwin64/849d656e_hxssl_md5.o
g++ -c -fvisibility=hidden -stdlib=libstdc++ -O2 -I/Users/ak/Developer/Haxe/libs/hxcpp/3,2,37/include -DHX_MACOS -m64 -Wno-parentheses -Wno-unused-value -Wno-format-extra-args -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=0 -x c++ -frtti -Wno-invalid-offsetof ./hxssl_base64.cpp -oobj/darwin64/849d656e_hxssl_base64.o
Error: ./hxssl_ssl.cpp:175:6: error: no matching function for call to 'ASN1_STRING_length'
        if( ASN1_STRING_length(asn1) != strlen(pattern) ){
            ^~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl/asn1.h:797:5: note: candidate function not viable: 1st argument ('const ASN1_STRING *' (aka 'const asn1_string_st *')) would lose const qualifier
int ASN1_STRING_length(ASN1_STRING *x) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
    ^
./hxssl_ssl.cpp:260:10: warning: enumeration values 'MatchFound', 'NoSANPresent', and 'Error' not handled in switch [-Wswitch]
        switch( result ){
                ^
1 warning and 1 error generated.
make: *** [ndll/Mac64/hxssl.ndll] Error 1
```

**Comment by Blank101** [comment]
Need someone with access to OS X to debug and fix this.

**Comment by yupswing** [comment]
I get the same error
Mac OS X 10.10.2

````sh
$ haxelib run hxcpp build.xml
g++ -c -fvisibility=hidden -stdlib=libstdc++ -O2 -I/usr/lib/haxe/lib/hxcpp/3,2,81/include -DHX_MACOS -m64 -Wno-parentheses -Wno-unused-value -Wno-format-extra-args -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=0 -x c++ -frtti -Wno-invalid-offsetof ./hxssl_sha1.cpp -oobj/darwin64/849d656e_hxssl_sha1.o
g++ -c -fvisibility=hidden -stdlib=libstdc++ -O2 -I/usr/lib/haxe/lib/hxcpp/3,2,81/include -DHX_MACOS -m64 -Wno-parentheses -Wno-unused-value -Wno-format-extra-args -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=0 -x c++ -frtti -Wno-invalid-offsetof ./hxssl_ssl.cpp -oobj/darwin64/849d656e_hxssl_ssl.o
Error: ./hxssl_ssl.cpp:175:6: error: no matching function for call to 'ASN1_STRING_length'
        if( ASN1_STRING_length(asn1) != strlen(pattern) ){
            ^~~~~~~~~~~~~~~~~~
/usr/include/openssl/asn1.h:797:5: note: candidate function not viable: 1st argument ('const ASN1_STRING *' (aka 'const asn1_string_st *')) would lose const qualifier
int ASN1_STRING_length(ASN1_STRING *x) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
    ^
./hxssl_ssl.cpp:260:10: warning: enumeration values 'MatchFound', 'NoSANPresent', and 'Error' not handled in switch [-Wswitch]
        switch( result ){
                ^
1 warning and 1 error generated.
````

**Comment by yupswing** [comment]
All right. I've got the problem.
http://stackoverflow.com/questions/7406946/why-is-apple-deprecating-openssl-in-macos-10-7-lion

So I've downloaded and compiled OpenSSL from the source at openssl.org

Now I just need to figure it out how to use my compiled OpenSSL instead of the system one.
Ideas? How can I tell to hxcpp to do that?

**Comment by yupswing** [comment]
Thanks to Jérémy Faivre I can compile now.
It was really really easy.

Change line 175 in hxssl_ssl.cpp to this
````cpp
if( ASN1_STRING_length((ASN1_STRING *)asn1) != strlen(pattern) ){
````

And it will compile (still a warning but not a big deal).

I've build and tested the ndll as well... everything looks all right

**Comment by Blank101** [comment]
Fixed on #44.
